/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PortfolioItem } from './types';

export const portfolioData: PortfolioItem[] = [
  {
    id: 'nefine-corporate-identity',
    title: '네파인 (Nefine) 글로벌 디자인 에이전시 CI',
    subtitle: '정교한 그리드와 미니멀한 라인들이 직조하는 시그니처 엠블럼',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/nefineci/800/600',
    innerImageUrl: 'https://picsum.photos/seed/nefineci-inner/800/600',
    desc: '창의성과 탁월한 엔지니어링의 완수 경계를 무너뜨리는 하이엔드 크리에이티브 디자인 그룹 Nefine의 정식 CI 시스템입니다.',
    concept: '알파벳 N의 기하학적 흐름 and 황금 비율 스플라인 곡선을 조화시켜 한 치의 오차도 허용하지 않는 현대적 이성과 감성 균형을 깊은 차콜과 비비드 그린으로 완성해냈습니다.',
    colors: ['#10AF85', '#111827', '#F3F4F6', '#FFFFFF'],
    client: 'Nefine Studio',
    year: '2026',
    highlights: ['디바이스 크기별 가독성을 위해 정교하게 조율된 마스터 벡터 빌드', 'SaaS 시스템 트레이 아이콘용 16px 초미세 심볼 포맷 제공', '명함 및 메탈 각인 사양 조안용 헤리티지 불박 인쇄 테스트']
  },
  {
    id: 'nefine-brand-book',
    title: '네파인 (Nefine) 2026 디자인 비전 브랜드 북',
    subtitle: '아키텍처 레이아웃 and 볼드 타이포의 품격을 담은 고사양 카탈로그',
    category: 'Brochure',
    imageUrl: 'https://picsum.photos/seed/nefinebb/800/600',
    innerImageUrl: 'https://picsum.photos/seed/nefinebb-inner/800/600',
    desc: '글로벌 리딩 에이전시 Nefine이 정립해 온 디자인 철학과 고도화된 스위스 모던 서체 패턴을 유기적으로 직조한 프리미엄 아카이브 가이드북입니다.',
    concept: '비코팅 친환경 순백색 수입 지류를 주축으로 과감한 여백비와 단색 잉크의 묵직함을 사용해 물리적인 매체로서의 영속적 가치를 극대화했습니다.',
    colors: ['#0E6B52', '#000000', '#F9F8F6', '#666666'],
    client: 'Nefine Studio Ltd.',
    year: '2026',
    highlights: ['하프 하드커버 제본과 핫스탬프 은박 양각 가공 가이드 수립', '그리드 기반 다단 정렬의 수학적 가독 레이아웃 도면 도출', '글로벌 파트너 프레젠테이션 무이레 방지 완벽 프린트 매치']
  },
  {
    id: 'atelier-fine',
    title: '아뜰리에파인 (Atelier Fine) 브로슈어',
    subtitle: '프리미엄 오가닉 뷰티 브랜드 브로슈어·리플렛 디자인',
    category: 'Brochure',
    imageUrl: 'https://picsum.photos/seed/cosmeticpkg/800/600',
    innerImageUrl: 'https://picsum.photos/seed/cosmeticpkg-inner/800/600',
    desc: '자연과의 공존을 지향하는 오가닉 뷰티 브랜드 아뜰리에파인의 라이프스타일 홍보 브로슈어 및 기프트 패키지 안내장 리플렛 컬렉션입니다.',
    concept: '자연 친화적이면서도 모던한 감성을 담은 미니멀 레이아웃과 친환경 오프셋 인쇄 지류 사용을 제안했습니다. 신뢰감을 더해주는 깊고 차분한 그린과 오프화이트 컬러를 메인으로 전개하여 브랜드의 아이덴티티를 명확히 표현했습니다.',
    colors: ['#10AF85', '#0E6B52', '#F9F8F6', '#222222'],
    client: '아뜰리에파인 주식회사',
    year: '2026',
    highlights: ['환경친화적 비코팅 지류 가이드 설계', '3단 리플렛 입체 레이아웃 및 접지 테스트', '브랜드 스토리텔링 카피라이팅 조율']
  },
  {
    id: 'good-bagel',
    title: 'Good Bagel (굿베이글) 브랜드 로고',
    subtitle: '베이글 전문 브랜드 시그니처 로고 & 무드 구축',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/bakerylogo/800/600',
    innerImageUrl: 'https://picsum.photos/seed/bakerylogo-inner/800/600',
    desc: '매일 아침 갓 구워낸 쫄깃하고 건강한 맛을 전하는 베이글 전문 브랜드, 굿베이글의 시그니처 비주얼 로고입니다.',
    concept: '둥글고 건강한 베이글의 형태적 특성에서 영감을 받은 클래식 둥근 서체와, 버터의 부드러움을 자아내는 마일드 그린 컬러를 결합한 브랜드 로고를 디자인했습니다. 친근하면서도 정제된 프렌치 감성의 베이커리 톤앤매너를 구축했습니다.',
    colors: ['#10AF85', '#E6C15C', '#1E1E1E', '#FFFFFF'],
    client: 'Good Bagel Co.',
    year: '2025',
    highlights: ['브랜드 워드 마크 & 엠블럼 개발', '가독성 높은 패키징 스탬프 및 라벨 응용 로고 설계', '식음료 오프라인 사용 시 가독성 보증 테스트 완료']
  },
  {
    id: 'blue-ocean',
    title: 'Blue Ocean (블루오션) 스쿠버 샵 로고',
    subtitle: '심해의 깊은 푸른 신비함을 담은 스쿠버 다이빙 클럽 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/diverlogo/800/600',
    innerImageUrl: 'https://picsum.photos/seed/diverlogo-inner/800/600',
    desc: '동해와 제주 등 국내외 바다의 아름다운 심해를 탐험하는 스쿠버 다이빙 클럽 블루오션의 시그니처 브랜드 로고입니다.',
    concept: '심해의 신비감을 전해주는 마린 블루와 안전한 다이빙을 상징하는 밝은 민트 색상을 유기적으로 연결했습니다. 고글과 파도의 파동을 기하학적으로 연출하여 활동적이면서 정통 신뢰감이 살아있는 실루엣 엠블럼위를 기획했습니다.',
    colors: ['#1E3A8A', '#06B6D4', '#F3F4F6', '#1E293B'],
    client: '블루오션 다이빙',
    year: '2026',
    highlights: ['수상/수중 장비 적용 전용 디자인 마크', '해상 보호 라이프스타일 엠블럼 굿즈 기획', '모든 아웃도어 의류 인쇄 호환용 방수 최적화 소스']
  },
  {
    id: 'nature-farm',
    title: 'Nature Farm (네이처팜) 유기농 마켓 로고',
    subtitle: '대지의 은혜와 수확물을 상징하는 친환경 유기농 마켓 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/organicfarm/800/600',
    innerImageUrl: 'https://picsum.photos/seed/organicfarm-inner/800/600',
    desc: '로컬 농가와의 상생을 바탕으로 갓 수확한 신선 유기농 농산물을 제공하는 네이처팜 협동조합의 유기농 브랜드 BI입니다.',
    concept: '풍요로운 곡식과 잎사귀 형태를 심플한 라인 아트로 빚어내어, 대지의 편안함과 현대적인 올가닉 가치를 일치시켰습니다. 브라운과 얼스 톤의 그린을 배치하여 소비자에게 안심과 영양 균형의 깊이를 전달합니다.',
    colors: ['#10AF85', '#8B5A2B', '#E8F5E9', '#333333'],
    client: '네이처팜 협동조합',
    year: '2025',
    highlights: ['자연 분해 펄프 패키징 전용 원라인 심볼 기획', '직거래 생산자 실명 보증 카드 라벨 제작', '에코 트렌드 감성의 크라프트지 인쇄 가이드 배포']
  },
  {
    id: 'slow-tempo',
    title: 'Slow Tempo (슬로우템포) 홈 카페 로고',
    subtitle: '지친 일상에 여유로운 한 잔을 선물하는 느린 템포 일상 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/homecafe/800/600',
    innerImageUrl: 'https://picsum.photos/seed/homecafe-inner/800/600',
    desc: '매일 바삐 움직이는 도심 속, 감각적인 핸드드립 커피와 명상적 공간을 조율하는 로컬 카페 브랜드 슬로우템포의 오리지널 로고입니다.',
    concept: '모래시계 속으로 똑똑 흐르는 커피 물방울을 미니멀하게 형상화하여 브랜드 아이덴티티에 함축했습니다. 베이지와 부드라운 차콜의 세련된 조합으로 따뜻하면서도 도회적인 커피 가치를 부각해냅니다.',
    colors: ['#DDB892', '#3D3D3D', '#ECE0D1', '#1A1A1A'],
    client: '슬로우템포 커피',
    year: '2026',
    highlights: ['도자기 식기 가마 인쇄 최적화 로고 스탬프 드로잉', '공간 유리창 시트 시공용 미니 레이아웃 구성', '핸드드립 블렌드 원두 패키지 태그 디자인 설계']
  },
  {
    id: 'pixel-craft',
    title: 'Pixel Craft (픽셀크래프트) 게임 스튜디오 로고',
    subtitle: '도트 감성의 기하학적 픽셀 아트 모티브 인디게임 개발 브랜드',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/gamestudio/800/600',
    innerImageUrl: 'https://picsum.photos/seed/gamestudio-inner/800/600',
    desc: '레트로 게임 무드를 현대 모바일 환경에 탑재해 독점적인 세계관을 발명해 내는 뉴트로 인디 게임 스튜디오 픽셀크래프트의 메인 엠블럼입니다.',
    concept: '레트로 입사각 블록과 정밀한 격자 선들의 스텝을 이용해 고전적인 크래프트 정신을 디지털 공간에 구현했습니다. 하이라이트 세라믹 퍼플과 아케이드 옐로우를 키 컬러로 차용하여 비주얼의 도회적 에너지와 선명도를 높였습니다.',
    colors: ['#8B5CF6', '#F59E0B', '#1E1B4B', '#FFFFFF'],
    client: '픽셀크래프트 게임즈',
    year: '2025',
    highlights: ['스팀/구글플레이 모바일 앱 아이콘 가독성 반응형 설계', '뉴트로 8비트 키체인 스토어 굿즈 디자인 매치', '벡터 오프라인 부스 한정판 굿즈 인쇄 가이드 수립']
  },
  {
    id: 'gourmet-house',
    title: 'Gourmet House (고메하우스) 프리미엄 소스 BI 로고',
    subtitle: '테이블 위의 품격을 바꾸는 가문 레시피 소스 브랜드 로고 디자인',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/gourmet/800/600',
    innerImageUrl: 'https://picsum.photos/seed/gourmet-inner/800/600',
    desc: '해외 유기농 엄선 천일염과 비법 에이징을 주축으로 맛의 완성도를 책임지는 프리미엄 다이닝 소스 전문 브랜드 고메하우스의 정식 BI 패밀리 심볼입니다.',
    concept: '고급 정통 가문을 연상케 하는 클래식 보르도 레드와 유럽 유서 깊은 상형 요소를 부드러운 아르누보 곡선 속에 배치했습니다. 프리미엄 등급을 암시하도록 텍스처 밀도를 높였으며 제품 신뢰도를 배가했습니다.',
    colors: ['#B91C1C', '#D97706', '#FFFDF9', '#111827'],
    client: '고메푸드컴퍼니',
    year: '2026',
    highlights: ['유리 병용 워터프루프 링 자재 점착 스티커 비주얼 통합', '골드 엠보싱 인쇄 적용 수입 지류 기획 구성', '파인다이닝 수입 수동 소스 수입 보틀 타이틀링 레이아웃']
  },
  {
    id: 'starlight-resort',
    title: 'Starlight Resort (별빛 리조트) 프리미엄 로고',
    subtitle: '울릉도 밤하늘 아래 자연 온천과 숙박을 겸하는 힐링 빌라 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/resort/800/600',
    innerImageUrl: 'https://picsum.photos/seed/resort-inner/800/600',
    desc: '맑고 고요한 숲속 울릉도 밤하늘의 쏟아지는 찬란한 은하수를 독점하는 하이엔드 자연 친화 리조트의 심볼 마크입니다.',
    concept: '밤하늘의 수많은 별빛 모티브와 리조트 정면 시그니처 글램 도어 형상을 통합한 라인 드로잉 기법을 사용했습니다. 신뢰와 영롱함을 함축하는 아쿠아 네이비 컬러 톤을 테마화하여 투숙객에게 압도적 안정성을 보증합니다.',
    colors: ['#0F172A', '#10AF85', '#E2E8F0', '#FFFFFF'],
    client: '주식회사 별빛리조트',
    year: '2025',
    highlights: ['실외 메탈 LED 현판 시안 1:1 정밀 하프 커팅 제작 수립', '객실 보증 가이드 카드 겸 웰컴 키트 전용 브랜딩 무드 연동', '모바일 컨시어지 앱 통합 로딩 전용 백터 심볼 조립 완료']
  },
  {
    id: 'bloom-flower',
    title: 'Bloom Flower (블룸플라워) 가드닝 샵 로고',
    subtitle: '식물이 주는 위안과 원예의 즐거움을 더하는 플라워 샵 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/flowershop/800/600',
    innerImageUrl: 'https://picsum.photos/seed/flowershop-inner/800/600',
    desc: '전문 플로리스트가 큐레이션한 꽃 예술 작품과 프리미엄 수입 가드닝 세라믹 화분을 유니크하게 소개하는 감각 가드닝 샵 브랜드 아이덴티티입니다.',
    concept: '피어나는 풍부한 모란 꽃잎과 클래식 손길 형태를 자연스런 연필 드로잉처럼 유기적으로 구성하여 화사하면서도 품격 있는 인상을 완성했습니다. 생기 있는 코랄 샌드와 마일드 로지 필드로 친절한 꽃집 무드를 연계했습니다.',
    colors: ['#F43F5E', '#10AF85', '#FFF1F2', '#2D2D2D'],
    client: '블룸플라워 아뜰리에',
    year: '2026',
    highlights: ['다양한 크기 포장 한지 스티커 가시성 전개', '플라워 바스켓용 메탈 클립 미니 팬던트 각인 가이드 제공', '모바일 주간 꽃 정기 배송 전용 박스 테이프 레이아웃 디자인']
  },
  {
    id: 'urban-fit',
    title: 'Urban Fit (어반핏) 피트니스 웨어 시그니처 로고',
    subtitle: '일하는 도심의 액티브한 에너지와 한계를 넘어서는 애슬레저 룩',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/gymwear/800/600',
    innerImageUrl: 'https://picsum.photos/seed/gymwear-inner/800/600',
    desc: '현대 빌딩 숲에서 일생과 활동의 흐름을 주도적으로 조율하며 활력을 충전하는 현대인을 위한 프리미엄 액티브 웨어 어반핏의 시그니처 워드마크입니다.',
    concept: '속도감 있는 슬래시 사선 라인과 강한 고딕 계열의 볼드 서체를 조합하여 타협하지 않는 역동적인 도전 정신과 패션을 동시에 각인시켰습니다. 무광 블랙 사틴 질감을 완벽하게 매치시켰습니다.',
    colors: ['#111827', '#F43F5E', '#E5E7EB', '#10AF85'],
    client: '어반핏 스포츠',
    year: '2026',
    highlights: ['의류 원단 부착용 러버 및 무독성 실리콘 라벨 고탄성 설계', '액티브 스포츠 러닝 용 트랙 패킹 지퍼백 라인 확장 무드 조립', '인스타그램 전용 모바일 최적화 미세 엠블럼 심볼 마크 개발']
  },
  {
    id: 'golden-crust',
    title: 'Golden Crust (골든크러스트) 베이커리 로고',
    subtitle: '전통 천연효모 버터 브레드 패밀리 엠블럼 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/bakery2/800/600',
    innerImageUrl: 'https://picsum.photos/seed/bakery2-inner/800/600',
    desc: '매일 전통 화덕 방식으로 밀가루를 발효시켜 가마솥풍 오븐에 천천히 구워내는 명장 브레드집 골든크러스트의 헤리티지 가치 브랜드 로고입니다.',
    concept: '황금빛 들녘과 따스하게 잘 익은 빵 표면의 크랙 질감에서 감흥을 이끌어내어 중후하고 고급스런 올드 월드 정통 마크를 세련되게 양각화했습니다.',
    colors: ['#E2B875', '#3E2723', '#FFF8E1', '#795548'],
    client: '골든크러스트 베이크샵',
    year: '2026',
    highlights: ['밀가루 포대 및 에코백 스크린 프린트 대응 시스템 개발', '풍부한 미식 헤리티지 감성 보증 마크 기획', '특화 패키징 스탬프 및 왁스 실 엠보스 가이드 수립']
  },
  {
    id: 'green-leaf',
    title: 'Green Leaf (그린리프) 비건 화장품 BI',
    subtitle: '동물 실험을 배제하는 진정 어린 마일드 비건 하우스',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/veganbeauty/800/600',
    innerImageUrl: 'https://picsum.photos/seed/veganbeauty-inner/800/600',
    desc: '유채꽃 씨앗과 산뜻한 식물 유래 진정 원료만을 추출하여 피부 장벽을 편안하게 안심시키는 순수 코스메틱의 정수인 그린리프의 에코 가치 시그니처 엠블럼입니다.',
    concept: '여리여리하게 돋아나는 여린 녹색 잎사귀 실루엣과 대지의 감성을 대변하는 유려한 서체를 믹싱하여 오가닉 무드와 모던함의 쾌적한 가치관을 관통했습니다.',
    colors: ['#4CAF50', '#1B5E20', '#E8F5E9', '#212121'],
    client: '그린리프 바이오',
    year: '2026',
    highlights: ['지속 만족 패키징 전용 원그리드 마크 설계', '용기 인쇄 시 미세 서체 깨짐 방지 해상 테스트 완료', '식물 추출물 전선 라벨용 미니 보증 디자인 패밀리룩 제공']
  },
  {
    id: 'brew-co',
    title: 'Brew & Co. (브루앤코) 수제 맥주 로고',
    subtitle: '대전 대표 양조장 프리미엄 크래프트 비어 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/craftbeer/800/600',
    innerImageUrl: 'https://picsum.photos/seed/craftbeer-inner/800/600',
    desc: '독창적인 홉 조합으로 신선하고 활력 넘치는 청량감을 빚어내는 로컬 수제 맥주 크루 Brew & Co.의 파워풀 메인 BI 로고입니다.',
    concept: '맥주 제조의 핵심인 홉(Hop) 리프와 역동적으로 넘치는 부드러운 거품의 볼륨감을 네오 레트로 무드로 승화시켜 모던 펍과 캔 패키지 레이블 어디에도 극강의 존재감을 선사합니다.',
    colors: ['#F59E0B', '#10AF85', '#111827', '#F3F4F6'],
    client: 'Brew & Co. 대전양조',
    year: '2025',
    highlights: ['캔 보틀 전면 알루미늄 라벨용 원형 엠블럼 설계', '코스터 및 맨투맨 굿즈 실크스크린 최적화 벡터화 완료', '모든 매장 네온사인 적용을 염두에 둔 강력한 라인 아트 빌드']
  },
  {
    id: 'monolith-tech',
    title: 'Monolith (모놀리스) IT 솔루션 로고',
    subtitle: '견고한 보안과 지능형 고집적 플랫폼 메인 워드마크',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/itmonolith/800/600',
    innerImageUrl: 'https://picsum.photos/seed/itmonolith-inner/800/600',
    desc: '서버 보안 및 분산 저장 테크놀로지를 리드하는 딥테크 벤처 기업 모놀리스인포섹의 기술 지향형 심포지엄 로고입니다.',
    concept: '하나의 거대한 기둥을 의미하는 모놀리스에서 착안하여 3차원 클러스터 블록들이 모여 강력하고 매끄러운 단일 보안 기둥을 형성하는 디지털 입체 조형미를 딥 세라믹 블루로 마감했습니다.',
    colors: ['#1E3A8A', '#3B82F6', '#0F172A', '#F1F5F9'],
    client: '모놀리스 컴퍼니',
    year: '2025',
    highlights: ['시스템 아키텍처 다이어그램 인포그래픽 수립', '온라인 콘솔 가시성 최적화 아이콘 에셋 빌드', '클라우드 인프라 파트너 제휴사 서명 인장 디자인']
  },
  {
    id: 'smart-home-iot',
    title: '스마트 리빙 IoT 플랫폼 상세페이지',
    subtitle: '한 손으로 조율하는 지능형 주거 생태계 런칭 스토어 상세페이지',
    category: 'DetailPage',
    imageUrl: 'https://picsum.photos/seed/iothome/800/600',
    innerImageUrl: 'https://picsum.photos/seed/iothome-inner/800/600',
    desc: '글로벌 기술 리딩 그룹의 신형 자가 IoT 센서 제품 라인업을 통합 소개하고 기술의 간편함을 강조하는 설득 중심의 하이퍼 커머스 웹 레이아웃입니다.',
    concept: '사용자가 느끼는 기술적 허들을 낮추기 위해 밝고 포근한 파스텔블루 컬러와 실생활 가구 배치 투시 그래픽을 조립하여 모던하고 감각적인 인터페이스로 유도했습니다.',
    colors: ['#3B82F6', '#10AF85', '#F0F9FF', '#1E293B'],
    client: '주식회사 넷스페이스',
    year: '2026',
    highlights: ['초 단위 스크롤 제어를 응용한 다이나믹 인터랙션 스토리보드 설계', '기기 연동 속도를 한눈에 체득할 수 있는 모바일 최적화 인포그래픽 제작', 'SaaS 제어 콘솔 디자인과의 연동 일체화 및 스마트스토어 규격 세팅']
  },
  {
    id: 'urban-garden-graphic',
    title: '어반 가든 (Urban Garden) 복합공간 월 그래픽',
    subtitle: '콘크리트 빌딩 숲 리크리에이티브 대형 친화 월 아트워크',
    category: 'WallGraphic',
    imageUrl: 'https://picsum.photos/seed/urbangarden/800/600',
    innerImageUrl: 'https://picsum.photos/seed/urbangarden-inner/800/600',
    desc: '테헤란로 중심가 복합문화빌딩 선큰 가든 및 입주민 휴게 홀 벽면을 아크릴 입체 구조물과 대형 일러스트로 장식한 프리미엄 수작 월 그래픽입니다.',
    concept: '지속 가능한 생명을 상징하는 대범한 아쿠아 블루그린과 자연 가든 패턴을 정밀 그리드 포맷 속에 배치해, 지친 시선에 시각적 청정 이완과 공간 격조를 완벽히 확보했습니다.',
    colors: ['#065F46', '#10AF85', '#F9FAFB', '#0F172A'],
    client: '랜드마크 개발 자산운용',
    year: '2026',
    highlights: ['실 가시 도안 정밀 시방서 및 벽면 아우트라인 1:1 수동 매칭', '내열성/내조성 아크릴 플레이트 레이저 하프 절단 가이드 제작', '인조 직조 부재 접합을 통한 친환경 방음 및 디자인 기능성 만족 보증']
  },
  {
    id: 'mono-records-pub',
    title: 'Mono Records (모노 레코즈) 아날로그 펍 로고',
    subtitle: '턴테이블 주파수와 빈티지 그루브를 믹싱한 뉴레트로 로고',
    category: 'Logo',
    imageUrl: 'https://picsum.photos/seed/monorec/800/600',
    innerImageUrl: 'https://picsum.photos/seed/monorec-inner/800/600',
    desc: '오직 아날로그 진공관 앰프와 무광 오리지널 바이닐 프레싱 원반으로만 사운드를 조율하는 하이엔드 오디오 펍 모노레코즈의 공식 시그니처 엠블럼입니다.',
    concept: '레코드 음색 기스 그루브 홈 라인을 정교한 격자 그리드 원으로 축약하고 깊은 재즈 나이트를 의미하는 인디고 블루 앤 골드로 세련되게 양질화했습니다.',
    colors: ['#1E1B4B', '#DFB15B', '#FFFDF9', '#4E2406'],
    client: '모노 레코즈 성수점',
    year: '2025',
    highlights: ['유리 전면 아크릴 엠보 네온사인 제작 백터 시트 정밀 가공 완료', '바 가죽 코스터 불박 낙인용 황동 스탬프 고해상 패턴 조립', '멤버십 회지 배포 및 보틀 오리지널 택 프레임 패밀리 룩 완성']
  },
  {
    id: 'oasis-stay-oasis',
    title: '오아시스 스테이 (Oasis Stay) 사막 웰컴 브로슈어',
    subtitle: '붉은 암벽 빌라 자궁 속 휴식을 약속하는 독채 풀빌라 웰컴 안내서',
    category: 'Brochure',
    imageUrl: 'https://picsum.photos/seed/oasisstay/800/600',
    innerImageUrl: 'https://picsum.photos/seed/oasisstay-inner/800/600',
    desc: '문명과 차단된 광활한 붉은 사막 한복판 고독 정수를 즐기는 하이엔드 웰니스 스पे셜 리조트 객실 매뉴얼 앤 마인드 웰컴북 컬렉션입니다.',
    concept: '대자연 오아시스 깊은 고요샘 물결 동심원을 단아한 아이보리 대리석 톤과 어스 오렌지 테라코타 컬러로 우아하게 프레이밍했습니다.',
    colors: ['#D97706', '#FCFBF9', '#78350F', '#1E293B'],
    client: '주식회사 오아시스 홀딩스',
    year: '2026',
    highlights: ['리조트 전용 아로마 입욕 솔트 점착 크래프트 라벨 통합 전개', '조식 가동 웰컴 메뉴 가죽판 쇠 고리 디테일 상세 설계 완료', '어메니티 비누 대나무 수공예 포장 크기 대응 마크 양각화 수립']
  },
  {
    id: 'architect-modern-house',
    title: '아키텍 (Architec) 정밀 건축 사무소 상세페이지',
    subtitle: '모놀리식 노출 콘크리트 미학 주택 실물 아카이브 온라인 쇼케이스',
    category: 'DetailPage',
    imageUrl: 'https://picsum.photos/seed/architect/800/600',
    innerImageUrl: 'https://picsum.photos/seed/architect-inner/800/600',
    desc: '불필요한 장식을 원천 걷어내고 자연 채광 공간 통로 설계만으로 삶의 밀도를 높여주는 정밀 주택 디자인 런칭 랜딩 상세 레이아웃입니다.',
    concept: '고고한 미니멀 다크 모노 차콜과 실버 알루미늄 메탈 질감 스냅 사진을 과감하고 단색 정론 그리드로 정렬하여 전문 고품격 신뢰를 부여했습니다.',
    colors: ['#111827', '#E5E7EB', '#FFFFFF', '#0369A1'],
    client: 'Architec Design Associates',
    year: '2026',
    highlights: ['시공 현장 3D 도면 스플릿 슬라이드 인터랙티브 컴포넌트 설계', '채광 일조 분석 기하 인포그래픽 그래픽 시스템 완수 제작 탑재', '우수 건축상 수훈 이력 증서를 한데 엮은 프리미엄 바이어 보증판 완성']
  }
];
